---
- name: Converge
  hosts: all
  vars:
    common_motd: |
      #*****************************************************************************#
      #                                !!!WARNING!!!                                #
      #                                                                             #
      # This system may be accessed and used only for authorized use only.          #
      #                                                                             #
      # Unauthorized use of this system or the information on this system could     #
      # result in criminal prosecution. Unauthorized access or use of this system   #
      # may subject violators to criminal, civil, and/or administrative action. By  #
      # accessing this system, you confirm that you are authorized to access this   #
      # system and consent that your actions are subject to monitoring.  All        #
      # information on this system may be intercepted, read, recorded, copied, and  #
      # disclosed by and to authorized personnel for official purposes, including   #
      # criminal investigations. Such information includes sensitive data encrypted #
      # to comply with confidentiality and privacy requirements. Access or use of   #
      # this system by any person, whether authorized or unauthorized, constitutes  #
      # consent to these terms.                                                     #
      #*****************************************************************************#

  tasks:
    - name: "Include Ansible Role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
