---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  push:
    branches:
      - master

defaults:
  run:
    # TODO: Update the Working Directory to the role name.
    working-directory: 'acgcloudworks.template'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          # TODO: Update the path to the role name.
          path: 'acgcloudworks.template'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

        # TODO: Uncomment the lines below if you wish to publish the role to Galaxy.
      # - name: Install Ansible.
      #   run: pip3 install ansible-base

      # - name: Trigger a new import on Galaxy.
      #   run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
